---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  galaxy: |
    ---
    collections:
      - community.windows
      - community.general
      - ansible.windows
      - community.aws
      - amazon.aws
      - ansible.netcommon
      - ansible.posix
      - kubernetes.core
  python: |
    git+https://github.com/ansible/ansible-sign
    git+https://github.com/ansible/ansible-builder.git@devel#egg=ansible-builder
    urllib3
    jmespath
    kubernetes
    pexpect

  system: |
    python3.11-devel [platform:rpm compile]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    net-tools [platform:rpm]
    lftp [platform:rpm]
    jq [platform:rpm]
    unzip [platform:rpm]
    azure-cli [platform:rpm]

  # python38-devel [platform:rpm compile]
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
    - RUN /usr/bin/python3 -m pip install --upgrade pip
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - RUN dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm
  append_final:
    - RUN az upgrade
    - RUN git lfs install --system
