- name: Configure provisioned Debian 12 VM. 
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Print hostname (debug)
      debug:
        msg: "{{ inventory_hostname }}"

    - name: Change hostname in /etc/hostname
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: "{{ current_name }}"
        line: "{{ server_name }}"
        state: present

    - name: Change hostname in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ current_name }}"
        replace: "{{ server_name }}"

    - name: Change IP address in /etc/network/interfaces
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        regexp: '{{ current_ip }}'
        replace: "{{ server_ip }}"

    - name: Update IP address in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ current_ip }}"
        replace: "{{ server_ip }}"

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        allow_change_held_packages: yes
        state: latest

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes

    - name: Remove machine-id
      ansible.builtin.command:
        cmd: rm /etc/machine-id
        sudo: true

    - name: Regenerate D-Bus machine UUID
      ansible.builtin.command:
        cmd: dbus-uuidgen --ensure
        sudo: true

    - name: Setup systemd machine ID
      ansible.builtin.command:
        cmd: systemd-machine-id-setup
        sudo: true

    - name: Remove old SSH host keys
      ansible.builtin.file:
        path: /etc/ssh/ssh_host_*
        state: absent
        sudo: true

    - name: Regenerate SSH host keys
      ansible.builtin.command:
        cmd: ssh-keygen -A
        sudo: true

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Rebooting the server to apply changes."
        sudo: true
