- name: Install Wazuh agent and configure to forward events to Wazuh manager
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Download Wazuh GPG key
      get_url:
        url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
        dest: "/tmp/GPG-KEY-WAZUH"
        mode: '0644'

    - name: Import Wazuh GPG key
      command: "gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import /tmp/GPG-KEY-WAZUH"
      args:
        creates: "/usr/share/keyrings/wazuh.gpg"

    - name: Set correct permissions on Wazuh GPG key
      file:
        path: "/usr/share/keyrings/wazuh.gpg"
        mode: '0644'

    - name: Add Wazuh repository
      lineinfile:
        path: "/etc/apt/sources.list.d/wazuh.list"
        line: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Wazuh agent
      apt:
        name: wazuh-agent
        state: present
        update_cache: yes
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager_ip }}"

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes

    - name: Enable and start Wazuh agent
      service:
        name: wazuh-agent
        state: started
        enabled: yes

    - name: Remove temporary GPG key file
      file:
        path: "/tmp/GPG-KEY-WAZUH"
        state: absent